language: python
python:
        - "3.6"
install:
        - pip install -r requirements.txt
        - pip install pytest coverage
script: 
        - python -m pytest
        - coverage run -m pytest
        - coverage report
