#!/bin/bash

# Shell script for generating API documentation and saving files to docs directory

pydoc3 -w flaskr/*.py

# Remove file path from files generated by pydoc and copy files into docs
sed 's/<a href="file.*a>//g' db.html > docs/db.html
sed 's/<a href="file.*a>//g' algorithm.html > docs/algorithm.html
sed 's/<a href="file.*a>//g' __init__.html > docs/__init__.html

# Delete original html documentation files
rm db.html
rm algorithm.html
rm __init__.html
